//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DxPlay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DxPlay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cookie.txt.
        /// </summary>
        internal static string CookieFile {
            get {
                return ResourceManager.GetString("CookieFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com/video-download/.
        /// </summary>
        internal static string DownloadUrl {
            get {
                return ResourceManager.GetString("DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com/history/.
        /// </summary>
        internal static string HistoryUrl {
            get {
                return ResourceManager.GetString("HistoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com.
        /// </summary>
        internal static string HomeUrl {
            get {
                return ResourceManager.GetString("HomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.xvideos.com.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com/account/signinform.
        /// </summary>
        internal static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com/favorite/69855543/cuong/.
        /// </summary>
        internal static string PlaylistUrl {
            get {
                return ResourceManager.GetString("PlaylistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proxy.txt.
        /// </summary>
        internal static string ProxyFile {
            get {
                return ResourceManager.GetString("ProxyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xvideos.com/.
        /// </summary>
        internal static string Referer {
            get {
                return ResourceManager.GetString("Referer", resourceCulture);
            }
        }
    }
}
